version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hotel-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - hotel-network

  redis:
    image: redis:alpine
    container_name: hotel-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hotel-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: hotel-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hotel-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: hotel-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hotel-network

volumes:
  mongodb_data:

networks:
  hotel-network:
    driver: bridge

