apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  # jwt-secret: base64 encoded JWT secret
  # mongodb-password: base64 encoded MongoDB password
  jwt-secret: eW91ci1zZWNyZXQta2V5  # your-secret-key
  mongodb-password: cGFzc3dvcmQ=  # password

